spring:
  application:
    name: networking1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/real_estate
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

